/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as budget from "../budget.js";
import type * as categories from "../categories.js";
import type * as finance from "../finance.js";
import type * as groups from "../groups.js";
import type * as group_invites from "../group_invites.js";
import type * as group_transactions from "../group_transactions.js";
import type * as http from "../http.js";
import type * as insights from "../insights.js";
import type * as transactions from "../transactions.js";
import type * as users from "../users.js";
import type * as user_settings from "../user_settings.js";
import type * as voting_sessions from "../voting_sessions.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  budget: typeof budget;
  categories: typeof categories;
  finance: typeof finance;
  groups: typeof groups;
  group_invites: typeof group_invites;
  group_transactions: typeof group_transactions;
  http: typeof http;
  insights: typeof insights;
  transactions: typeof transactions;
  users: typeof users;
  user_settings: typeof user_settings;
  voting_sessions: typeof voting_sessions;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
